name: reyuflow_gate_scheduler
description: A smart GATE scheduler with voice + text assistant.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^15.1.1
  flutter_tts: ^3.8.2
  speech_to_text: ^6.3.0
  http: ^0.13.6
  shared_preferences: ^2.2.2
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
